// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdUo0szLyS7UTplIYE1yYXwKN47W5CIKM',
    appId: '1:892780749225:web:4afdb42deefc4ba29324b8',
    messagingSenderId: '892780749225',
    projectId: 'chatme-48e97',
    authDomain: 'chatme-48e97.firebaseapp.com',
    storageBucket: 'chatme-48e97.appspot.com',
    measurementId: 'G-ZHREXJ98PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYU-JILoABrHp4AbvBI_gQ1X5L8UlQF80',
    appId: '1:892780749225:android:89389d29cd4bac4a9324b8',
    messagingSenderId: '892780749225',
    projectId: 'chatme-48e97',
    storageBucket: 'chatme-48e97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAjN8aSKkHte4DsZqNnyTiC6JHxeOoZA',
    appId: '1:892780749225:ios:49943ca68c3d6e359324b8',
    messagingSenderId: '892780749225',
    projectId: 'chatme-48e97',
    storageBucket: 'chatme-48e97.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQAjN8aSKkHte4DsZqNnyTiC6JHxeOoZA',
    appId: '1:892780749225:ios:36d7e47a5d828d7f9324b8',
    messagingSenderId: '892780749225',
    projectId: 'chatme-48e97',
    storageBucket: 'chatme-48e97.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
